services:
  - type: web
    name: peluqueria-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: SHEET_ID
        value: 16azlcSMh1_zpxNQNbqyNuMBxzCFmYGSF2rWZPf2WR6I
      - key: PYTHON_VERSION
        value: 3.12.0